### ISSUE TITLE
Doesn't work on python 3.11 version

### ISSUE THREAD

**Issue by jus7nyan** [l-n-s/i2plib#3]
when running any code with this library, this error appears.
when running the wget example:
```
Traceback (most recent call last):
  File "/home/justnyan/MyProject/JUNQ-protocol-python/test/i2p.py", line 36, in <module>
    loop.run_until_complete(wget(i2plib.get_sam_address(), loop, url))
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/justnyan/MyProject/JUNQ-protocol-python/test/i2p.py", line 12, in wget
    async with i2plib.Session(session_name, sam_address=sam_address, loop=loop):
  File "/usr/local/lib/python3.11/dist-packages/i2plib-0.0.14-py3.11.egg/i2plib/aiosam.py", line 198, in __aenter__
  File "/usr/local/lib/python3.11/dist-packages/i2plib-0.0.14-py3.11.egg/i2plib/aiosam.py", line 106, in create_session
  File "/usr/local/lib/python3.11/dist-packages/i2plib-0.0.14-py3.11.egg/i2plib/aiosam.py", line 28, in get_sam_socket
  File "/usr/lib/python3.11/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                         ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'loop'
```

**Comment by barracuda156** [comment]
@jus7nyan Maybe just remove those? https://github.com/NoneGG/aredis/issues/207

**Comment by SergSel2006** [comment]
Python 3.11 deprecated `loop` paramether so it's expectable. For 3.11 and later, you may jusr remove it from `asyncio.create_connection()` in the get_sam_socket() in the aiosam.py file
